# Generated by Django 4.2.11 on 2026-03-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_recurring_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=255)),
                ('cc_email', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='dashboard.facture')),
            ],
            options={
                'verbose_name': 'Historique envoi facture',
                'verbose_name_plural': 'Historique envoi factures',
                'ordering': ['-sent_at'],
            },
        ),
    ]
