# Generated by Django 4.2.11 on 2026-03-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_factureemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ice',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ICE'),
        ),
    ]
