# Generated by Django 4.2.11 on 2026-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_client_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='hors_taxe',
            field=models.BooleanField(default=False, verbose_name='Hors taxe'),
        ),
    ]
